### ISSUE TITLE
save-metadata error

### ISSUE THREAD

**Issue by rdrr** [hexmode/mediawiki-el#1]
I'm getting an error trying to connect to any wikipedia article.  The debugger says:

Posting to: http://en.wikipedia.org/w/api.php
Contacting host: en.wikipedia.org:80
Examine the ' _http en.wikipedia.org:80_-614858' buffer called from 'url-http-response-post-process:3'.
mediawiki-save-metadata: Wrong type argument: listp, 0

This happens no matter how I configure the Mediawiki Site alist.

**Comment by hexmode** [comment]
rdrr writes:

> Examine the ' *http en.wikipedia.org:80*-614858' buffer ....

Could you post the contents for that buffer?  You might need to make
sure it doesn't contain any passwords.

**Comment by hexmode** [comment]
closing this.
