### ISSUE TITLE
HTTPS breaking mediawiki.el?

### ISSUE THREAD

**Issue by curlyturkey** [hexmode/mediawiki-el#10]
Haven't been able to connect with mediawiki.el since July.  Behind the proxy at work I get:

      Error: 403, Insecure Request Forbidden - use HTTPS - https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html

Which tells us:

TL;DR:
----
* All access to Wikimedia production sites/APIs should use https://
URLs, not http:// -- your bot/tool will break in the near future if it
does not!
* 2016-06-12 - insecure access is unsupported; starting on this date
we plan to break (deny with 403) 10% of all insecure requests randomly
as a wake-up call.
* 2016-07-12 - we plan to break all insecure requests.

I tried changing all http manually to https in the source, but then I get:

     The plain HTTP request was sent to HTTPS port

When I try to connect at home (with no proxy) it just hangs, whether I use http (Contacting host: en.wikipedia.org:80 ...) or https (Contacting host: en.wikipedia.org:443 ...)

**Comment by hexmode** [comment]
You should use
  M-x customize-variable RET mediawiki-site-alist RET
instead of modifying the source.

I'm able to successfully connect using https.

Could you enable debugging and re-do the request?
  (setq mediawiki-debug t)

Buffers titled " *http en.wikipedia.org:443*" or " *http en.wikipedia.org:443*-XXXX" (where XXXX is a number) will be produced.  Could you post what you see in those (after removing your password)?

**Comment by curlyturkey** [comment]
Thanks.  I can connect using https now at home, but at work behind a proxy
I get:

Posting to: https://en.wikipedia.org/w/api.php
Contacting host: XXX.XX.X.XX:12080
xml-parse-tag-1: XML: (Not Well-Formed) Invalid end tag `body' (expecting
`hr')


With debugging enabled I get:

Debugger entered--Lisp error: (error "The server encountered an error:
(badtoken) Invalid token")
  signal(error ("The server encountered an error: (badtoken) Invalid
token"))
  error("The server encountered an error: (%s) %s" "badtoken" "Invalid
token")
  (let* ((err (cadr (assq (quote error) (cddr result)))) (err-code (cdr
(assq (quote code) err))) (err-info (cdr (assq (quote info) err)))) (error
"The server encountered an error: (%s) %s" err-code err-info))
  (progn (let* ((err (cadr (assq (quote error) (cddr result)))) (err-code
(cdr (assq (quote code) err))) (err-info (cdr (assq (quote info) err))))
(error "The server encountered an error: (%s) %s" err-code err-info)))
  (if (assq (quote error) (cddr result)) (progn (let* ((err (cadr (assq
(quote error) (cddr result)))) (err-code (cdr (assq (quote code) err)))
(err-info (cdr (assq (quote info) err)))) (error "The server encountered an
error: (%s) %s" err-code err-info))))
  (let* ((raw (url-http-post (mediawiki-make-api-url sitename) (delq nil
(append args (list (cons "format" "xml") (cons "action" action)))) (string=
action "upload"))) (result (assoc (quote api) (let ((temp-buffer
(generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer
temp-buffer) (unwind-protect (progn ... ...) (and ... ...))))))) (if result
nil (error "There was an error parsing the result of the API call")) (if
(assq (quote error) (cddr result)) (progn (let* ((err (cadr (assq ...
...))) (err-code (cdr (assq ... err))) (err-info (cdr (assq ... err))))
(error "The server encountered an error: (%s) %s" err-code err-info)))) (if
(cddr result) (let ((action-res (assq (intern action) (cddr result)))) (if
action-res nil (error "Didn't see action name in the result list"))
action-res) t))
  mediawiki-api-call("Wikipedia" "edit" (("title" . "Night of January
16th") ("text" . "{{good article}} ...

... the text source of the article ...

...")
  (if mediawiki-page-title (mediawiki-save-page mediawiki-site
mediawiki-page-title summary (buffer-substring-no-properties (point-min)
(point-max))) (error "Error: %s is not a mediawiki document" (buffer-name)))
  mediawiki-save("")
  call-interactively(mediawiki-save nil nil)
  command-execute(mediawiki-save)

... or if I try to log in again:

Debugger entered--Lisp error: (error "XML: (Not Well-Formed) Invalid end
tag `body' (expecting `hr')")
  signal(error ("XML: (Not Well-Formed) Invalid end tag `body' (expecting
`hr')"))
  error("XML: (Not Well-Formed) Invalid end tag `%s' (expecting `%s')"
"body" "hr")
  xml-parse-tag-1(nil nil)
  xml-parse-tag-1(nil nil)
  xml-parse-tag-1(nil nil)
  xml--parse-buffer(nil nil)
  xml-parse-region(1 264)
  (progn (insert raw) (xml-parse-region (point-min) (point-max)))
  (unwind-protect (progn (insert raw) (xml-parse-region (point-min)
(point-max))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn
(insert raw) (xml-parse-region (point-min) (point-max))) (and (buffer-name
temp-buffer) (kill-buffer temp-buffer))))
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer
(set-buffer temp-buffer) (unwind-protect (progn (insert raw)
(xml-parse-region (point-min) (point-max))) (and (buffer-name temp-buffer)
(kill-buffer temp-buffer)))))
  (assoc (quote api) (let ((temp-buffer (generate-new-buffer " *temp*")))
(save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn
(insert raw) (xml-parse-region (point-min) (point-max))) (and (buffer-name
temp-buffer) (kill-buffer temp-buffer))))))
  (let* ((raw (url-http-post (mediawiki-make-api-url sitename) (delq nil
(append args (list (cons "format" "xml") (cons "action" action)))) (string=
action "upload"))) (result (assoc (quote api) (let ((temp-buffer
(generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer
temp-buffer) (unwind-protect (progn ... ...) (and ... ...))))))) (if result
nil (error "There was an error parsing the result of the API call")) (if
(assq (quote error) (cddr result)) (progn (let* ((err (cadr (assq ...
...))) (err-code (cdr (assq ... err))) (err-info (cdr (assq ... err))))
(error "The server encountered an error: (%s) %s" err-code err-info)))) (if
(cddr result) (let ((action-res (assq (intern action) (cddr result)))) (if
action-res nil (error "Didn't see action name in the result list"))
action-res) t))
  mediawiki-api-call("Wikipedia" "login" (("lgname" . "Curly Turkey")
("lgpassword" . "XXXXXXXX") nil))
  (cadr (mediawiki-api-call (symbol-value (quote --cl-sitename--)) "login"
(symbol-value (quote --cl-args--))))
  (let ((--cl-result-- (cadr (mediawiki-api-call (symbol-value (quote
--cl-sitename--)) "login" (symbol-value (quote --cl-args--)))))) (progn (if
(string= (cdr (assq (quote result) (symbol-value (quote --cl-result--))))
"NeedToken") (progn (let* ((v (quote --cl-result--))) (set v (cadr
(mediawiki-api-call ... "login" ...)))))) (if (string= "Success" (cdr
(assoc (quote result) (symbol-value (quote --cl-result--))))) (progn
(symbol-value (quote --cl-sitename--))))))
  (progn (defvar --cl-result--) (let ((--cl-result-- (cadr
(mediawiki-api-call (symbol-value (quote --cl-sitename--)) "login"
(symbol-value (quote --cl-args--)))))) (progn (if (string= (cdr (assq
(quote result) (symbol-value ...))) "NeedToken") (progn (let* ((v ...))
(set v (cadr ...))))) (if (string= "Success" (cdr (assoc (quote result)
(symbol-value ...)))) (progn (symbol-value (quote --cl-sitename--)))))))
  (let ((--cl-args-- (list (cons "lgname" (symbol-value (quote
--cl-user--))) (cons "lgpassword" (symbol-value (quote --cl-pass--))) (if
(symbol-value (quote --cl-dom--)) (progn (cons "lgdomain" (symbol-value
...))))))) (progn (defvar --cl-result--) (let ((--cl-result-- (cadr
(mediawiki-api-call (symbol-value ...) "login" (symbol-value ...)))))
(progn (if (string= (cdr (assq ... ...)) "NeedToken") (progn (let* (...)
(set v ...)))) (if (string= "Success" (cdr (assoc ... ...))) (progn
(symbol-value (quote --cl-sitename--))))))))
  (progn (defvar --cl-args--) (let ((--cl-args-- (list (cons "lgname"
(symbol-value (quote --cl-user--))) (cons "lgpassword" (symbol-value (quote
--cl-pass--))) (if (symbol-value (quote --cl-dom--)) (progn (cons
"lgdomain" ...)))))) (progn (defvar --cl-result--) (let ((--cl-result--
(cadr (mediawiki-api-call ... "login" ...)))) (progn (if (string= (cdr ...)
"NeedToken") (progn (let* ... ...))) (if (string= "Success" (cdr ...))
(progn (symbol-value ...))))))))
  (let ((--cl-sitename-- sitename)) (progn (defvar --cl-args--) (let
((--cl-args-- (list (cons "lgname" (symbol-value ...)) (cons "lgpassword"
(symbol-value ...)) (if (symbol-value ...) (progn ...))))) (progn (defvar
--cl-result--) (let ((--cl-result-- (cadr ...))) (progn (if (string= ...
"NeedToken") (progn ...)) (if (string= "Success" ...) (progn ...))))))))
  (progn (defvar --cl-sitename--) (let ((--cl-sitename-- sitename)) (progn
(defvar --cl-args--) (let ((--cl-args-- (list (cons "lgname" ...) (cons
"lgpassword" ...) (if ... ...)))) (progn (defvar --cl-result--) (let
((--cl-result-- ...)) (progn (if ... ...) (if ... ...))))))))
  (let ((--cl-dom-- (if (symbol-value (quote --cl-dom-loaded--)) (progn (if
(string= "" (symbol-value ...)) (read-string "LDAP Domain: ") (symbol-value
(quote --cl-dom-loaded--))))))) (progn (defvar --cl-sitename--) (let
((--cl-sitename-- sitename)) (progn (defvar --cl-args--) (let ((--cl-args--
(list ... ... ...))) (progn (defvar --cl-result--) (let (...) (progn ...
...))))))))
  (progn (defvar --cl-dom--) (let ((--cl-dom-- (if (symbol-value (quote
--cl-dom-loaded--)) (progn (if (string= "" ...) (read-string "LDAP Domain:
") (symbol-value ...)))))) (progn (defvar --cl-sitename--) (let
((--cl-sitename-- sitename)) (progn (defvar --cl-args--) (let ((--cl-args--
...)) (progn (defvar --cl-result--) (let ... ...))))))))
  (let ((--cl-dom-loaded-- (mediawiki-site-domain sitename))) (progn
(defvar --cl-dom--) (let ((--cl-dom-- (if (symbol-value (quote
--cl-dom-loaded--)) (progn (if ... ... ...))))) (progn (defvar
--cl-sitename--) (let ((--cl-sitename-- sitename)) (progn (defvar
--cl-args--) (let (...) (progn ... ...))))))))
  (progn (defvar --cl-dom-loaded--) (let ((--cl-dom-loaded--
(mediawiki-site-domain sitename))) (progn (defvar --cl-dom--) (let
((--cl-dom-- (if (symbol-value ...) (progn ...)))) (progn (defvar
--cl-sitename--) (let ((--cl-sitename-- sitename)) (progn (defvar
--cl-args--) (let ... ...))))))))
  (let ((--cl-pass-- (or (mediawiki-site-password sitename) password
(read-passwd "Password: ")))) (progn (defvar --cl-dom-loaded--) (let
((--cl-dom-loaded-- (mediawiki-site-domain sitename))) (progn (defvar
--cl-dom--) (let ((--cl-dom-- (if ... ...))) (progn (defvar
--cl-sitename--) (let (...) (progn ... ...))))))))
  (progn (defvar --cl-pass--) (let ((--cl-pass-- (or
(mediawiki-site-password sitename) password (read-passwd "Password: "))))
(progn (defvar --cl-dom-loaded--) (let ((--cl-dom-loaded--
(mediawiki-site-domain sitename))) (progn (defvar --cl-dom--) (let
((--cl-dom-- ...)) (progn (defvar --cl-sitename--) (let ... ...))))))))
  (let ((--cl-user-- (or (mediawiki-site-username sitename) username
(read-string "Username: ")))) (progn (defvar --cl-pass--) (let
((--cl-pass-- (or (mediawiki-site-password sitename) password (read-passwd
"Password: ")))) (progn (defvar --cl-dom-loaded--) (let ((--cl-dom-loaded--
(mediawiki-site-domain sitename))) (progn (defvar --cl-dom--) (let (...)
(progn ... ...))))))))
  (progn (defvar --cl-user--) (let ((--cl-user-- (or
(mediawiki-site-username sitename) username (read-string "Username: "))))
(progn (defvar --cl-pass--) (let ((--cl-pass-- (or (mediawiki-site-password
sitename) password (read-passwd "Password: ")))) (progn (defvar
--cl-dom-loaded--) (let ((--cl-dom-loaded-- ...)) (progn (defvar
--cl-dom--) (let ... ...))))))))
  mediawiki-do-login("Wikipedia")
  (setq mediawiki-site (mediawiki-do-login site))
  (progn (setq mediawiki-site (mediawiki-do-login site)))
  (if (or (eq nil mediawiki-site) (not (string-equal site mediawiki-site)))
(progn (setq mediawiki-site (mediawiki-do-login site))))
  mediawiki-site()
  call-interactively(mediawiki-site record nil)
  command-execute(mediawiki-site record)
  execute-extended-command(nil "mediawiki-site")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by hexmode** [comment]
curlyturkey writes:

> Thanks.  I can connect using https now at home, but at work behind a proxy
> I get:
>
> Posting to: https://en.wikipedia.org/w/api.php
> Contacting host: XXX.XX.X.XX:12080
> xml-parse-tag-1: XML: (Not Well-Formed) Invalid end tag `body' (expecting
> `hr')

You need to set your proxy.  Use customize on url-proxy-services.  If
these are set in your environment variables, execute the following:

    (require 'url-methods)
    (url-scheme-register-proxy "http")
    (url-scheme-register-proxy "https")

**Comment by curlyturkey** [comment]
It makes no difference.  This is the code I'd been using to toggle the
proxy:

(setq *current-proxy* nil)
(defun toggle-http-proxy ()
  (if
      (not (equal *current-proxy* 'work))
      (setq url-proxy-services '(("http" . "172.25.0.24:12080")
                                 ("https" . "172.25.0.24:12080")
                                 ("ftp" . "172.25.0.24:12080"))
            *current-proxy* 'work)
    (setq url-proxy-services nil
          *current-proxy* 'no-proxy)))

**Comment by hexmode** [comment]
curlyturkey writes:

> It makes no difference.

Does M-x eww RET do anything?

**Comment by curlyturkey** [comment]
It hangs until it times out:

 Contacting host: duckduckgo.com:443
 open-network-stream: Failed connect: connection timed out

**Comment by hexmode** [comment]
Since it is hanging, it looks like Emacs can not connect to the 'net.  This probably means that either your proxy information is wrong.

**Comment by curlyturkey** [comment]
Weird ... it connected fine until I upgraded mediawiki.el in July, but I
guess mediawiki.el is not to blame.

**Comment by hexmode** [comment]
You could downgrade to the previous version.  If it works again, let me know.

**Comment by hexmode** [comment]
Another way to ensure this is a proxy problem: turn on debugging and look at the ` *http` buffers.  If they contain responses from Wikipedia, then this is a mediawiki.el problem.  If the contain something else, this is likely a proxy configuration problem.
