### ISSUE TITLE
Dashes

### ISSUE THREAD

**Issue by Kautilya3** [hexmode/mediawiki-el#12]
Whenever a page title contains dashes, e.g., Hindu-Arabic numeral system, where the "-" is supposed to be an en dash, I can't get mediawiki-open to work. I suppose it is some character encoding problem.
Using Gnu Emacs 24.5 on Windows PC. Version of mediawiki is 2.2.3. -- Kautilya3

**Comment by hexmode** [comment]
Note that [Hindu-Arabic numeral system](https://en.wikipedia.org/w/index.php?title=Hindu-Arabic_numeral_system&redirect=no) (no en-dash) exists and redirects to [Hindu–Arabic numeral system](https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system) (en-dash).

You can set up emacs to manage en-dashes where you need them, but this is a wiki-policy issue, not a MediaWiki issue.

To enter an en-dash, you can type `C-x 8 RET EN DASH RET` or `C-x 8 RET 2013 RET`.  Key combinations like this can be found by putting the point over the character you want and typing `M-x describe-char RET`.  For example, doing that for an en-dash gives this help buffer:
````
             position: 18 of 65 (26%), column: 17
            character: – (displayed as –) (codepoint 8211, #o20023, #x2013)
    preferred charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0x2013
               script: symbol
               syntax: _ 	which means: symbol
             category: .:Base, >:Not at bol, c:Chinese, j:Japanese
             to input: type "C-x 8 RET 2013" or "C-x 8 RET EN DASH"
          buffer code: #xE2 #x80 #x93
            file code: #xE2 #x80 #x93 (encoded by coding system utf-8)
              display: by this font (glyph code)
    xft:-b&h-Go-normal-normal-normal-*-16-*-*-*-*-0-iso10646-1 (#xA1)

Character code properties: customize what to show
  name: EN DASH
  general-category: Pd (Punctuation, Dash)
  decomposition: (8211) ('–')

There are text properties here:
  face                 font-lock-variable-name-face
  fontified            t
````

Note the keystrokes are shown by _to input:_.
