### ISSUE TITLE
Extra ")" on #1027 

### ISSUE THREAD

**Issue by boudiccas** [hexmode/mediawiki-el#18]
mediawiki.el won't compile because of the extra ")" on line 1027, but when its removed it can be compiled and emacs will load properly. And then I can go back to editing my mediawiki files.

Apart from that very small problem, it all works togethor very well. Thank you :)

**Comment by CyberShadow** [comment]
https://github.com/hexmode/mediawiki-el/pull/19

**Comment by hexmode** [comment]
fixed.
