### ISSUE TITLE
Mediawiki mode stopped working after upgrading to the latest 20150403 from Melpa

### ISSUE THREAD

**Issue by lumeng** [hexmode/mediawiki-el#2]
In Emacs 24.3.1 or the newest 24.5, I upgraded Mediawiki package to the latest version, 20150403... from Melpa, using the package manager. After restarting, I found that I can't access remote Mediawiki sites any more, after inputting user name and password as usual, I got a

Wrong type argument: listp, 0 
error in the mini buffer.

See http://emacs.stackexchange.com/questions/12639/mediawiki-mode-stopped-working-after-upgrading-to-the-latest-20150403 for details.

**Comment by hexmode** [comment]
Meng Lu writes:

> Wrong type argument: listp, 0 
> error in the mini buffer.
>
> See http://emacs.stackexchange.com/questions/12639/mediawiki-mode-stopped-working-after-upgrading-to-the-latest-20150403 for details. 

Do you normally have to use a proxy to access the internet?  Does

  M-x eww RET test RET

pull up a list of search results for "test"?

**Comment by lumeng** [comment]
> Do you normally have to use a proxy to access the internet?
No.

>Does
>
>M-x eww RET test RET
>
>pull up a list of search results for "test"?

Yes, it does.

**Comment by thibaultmarin** [comment]
@hexmode, could you please review https://github.com/hexmode/mediawiki-el/pull/3#issuecomment-113191730, it may fix this issue (and possibly #1).

**Comment by hexmode** [comment]
@thibaultmarin sorry for just now looking at that.  The pull request you mention only makes whitespace changes, which I why I dismissed it.  Your comment, though, makes it what you wanted clearer.

**Comment by hexmode** [comment]
Looks like a bug in github (or just something I don't understand) since the link to [312c637a](https://github.com/hexmode/mediawiki-el/commit/312c637a8da78772871994cb61b0ae68b37f3add#diff-3e3b6232afb4c1498ecf2cfaf9129f41R1169) doesn't show the change and a [visual examination](https://github.com/hexmode/mediawiki-el/pull/3/files) of your pull request doesn't show the change, but "git diff" does show the change.

**Comment by roymath** [comment]
I assume that this is still open, since the melpa version shows the same issue (Jan/2017). Do I manually patch, or is there a better way?

**Comment by hexmode** [comment]
The only patch referred to here 312c637a has been merged.  Could you tell me what problem you are seeing?

**Comment by roymath** [comment]
I see what's happening now.. the version from MELPA stable (https://stable.melpa.org/packages/) is broken, but the latest MELPA version ("http://melpa.org/packages/") of mediawiki.el has the right fix.

Would it be possible to fix melpa stable as well?

**Comment by heroxbd** [comment]
Bump, I am having the same bug with the version in melpa-stable, making it essentially unusable.  Could you please release a stable version?

**Comment by danielkschneider** [comment]
Hi
I do encounter a bug for version 2.2.9, emacs version = 24.5.1 on Ubuntu 16.x
 if: Symbol's value as variable is void: url-user-agent
Since the included packages were broken I installed from here. Same problem.
Anything I could do for this ? thanks !

**Comment by hexmode** [comment]
This should be fixed.  If you experience problems, it is probably a new bug and you should open a new issue.
