### ISSUE TITLE
Symbol’s function definition is void: string-trim

### ISSUE THREAD

**Issue by dertuxmalwieder** [hexmode/mediawiki-el#20]
I use Emacs 25.1 on Windows 10.

After installing `mediawiki.el` from MELPA and `require`ing the extension, I can't do anything:

    M-x mediawiki-site RET Wikipedia RET
    > url-compat-retrieve: Symbol’s function definition is void: string-trim

Why?

**Comment by hexmode** [comment]
I'm not sure.  [string-trim is included in Emacs 24.4+](http://emacsredux.com/blog/2014/02/02/a-peek-at-emacs-24-dot-4-new-string-manipulation-functions/).  If you load `M-x load-lib RET subr-x RET` does it work?

**Comment by dertuxmalwieder** [comment]
Well, I can `eval-expression` `(string-trim whatever)` after loading the library... it should, I guess?
