### ISSUE TITLE
mediawiki-save-page: Need an edit token!

### ISSUE THREAD

**Issue by JianleiZhang** [hexmode/mediawiki-el#22]
mediawiki-version "2.2.8"
GNU Emacs 24.5.1

**Comment by awalker4** [comment]
I was also seeing this error whenever I tried to use mediawiki-save. Not sure if this is the right fix, but I got it to work by uncommenting the line in mediawiki-api-query-revisions:

`;                            (cons "intoken" (mediawiki-api-param "edit"))`
