### ISSUE TITLE
mediawiki-site not found

### ISSUE THREAD

**Issue by davidhedlund** [hexmode/mediawiki-el#24]
1: I installed ELPA package successfully with
> M-x package-install RET mediawiki RET

2: Configured .emacs (with my proper username and password that I use on ArchWiki):
> (setq mediawiki-site-alist
>       (append '(("ArchWiki" "https://wiki.archlinux.org/" "username" "password" "Main page"))
>               mediawiki-site-alist))

3: Restarted Emacs

4: M-x mediawiki TAB doesn't list ```mediawiki-site``` described on [mediawiki-el](https://wiki.archlinux.org/index.php/Mediawiki-el), only:
> mediawiki-draft
> mediawiki-draft-buffer
> mediawiki-draft-page

What am I doing wrong?

**Comment by isacdaavid** [comment]
There's an easy way around this. In my setup `mediawiki-site` and a bunch other commands are defined only after opening a token MediaWiki buffer with `mediawiki-draft`. You'll probably also have to follow #22 to be able to upload changes.

**Comment by davidhedlund** [comment]
@isacdaavid Thanks but I want this bug to be fixed before I start using mediawiki-el at all. Are you a developer for this project?

**Comment by isacdaavid** [comment]
@davidhedlund:
> Are you a developer for this project?

Not at all. I would also like to see those properly fixed. Just sharing the dirty hack...

**Comment by davidhedlund** [comment]
@isacdaavid Thanks.

**Comment by hexmode** [comment]
Fixed in 9e55dfea1ce0040dd544e78e6f645634275ea37

I would accept pull requests...

**Comment by davidhedlund** [comment]
@hexmode Thank you.

**Comment by davidhedlund** [comment]
@hexmode Which version will the fix appear in?

**Comment by hexmode** [comment]
This is fixed in 2.2.9.

**Comment by davidhedlund** [comment]
@hexmode Good to know.
