### ISSUE TITLE
Can't save edit on the archwiki

### ISSUE THREAD

**Issue by Titan-C** [hexmode/mediawiki-el#26]
I tryed to use this package for the archlinux wiki. I can login and browse any page but I can't save my changes. I'm not good in Elisp, nor in the MediaWiki API.

I understand the error is not here https://github.com/hexmode/mediawiki-el/blob/master/mediawiki.el#L1435 but emacs does not concatenate a number with a string and the error message.

The error I get is "(badtoken) Invalid CSRF token"

**Comment by hexmode** [comment]
I think this should be supported now.
