### ISSUE TITLE
login tokens for mediawiki <1.27

### ISSUE THREAD

**Issue by heroxbd** [hexmode/mediawiki-el#28]
From https://www.mediawiki.org/wiki/API:Login#The_login_action, query of login tokens is different before and after mediawiki 1.27.  The present implementation is for >=1.27 only.  Is there any plans to support sites by older mediawiki?

**Comment by hexmode** [comment]
I know recent versions of MW are supported, but not how far back the support goes.  At this point, I do not see a reason to support [un-supported versions of MediaWiki](https://www.mediawiki.org/wiki/Version_lifecycle).
