### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by mavit** [hexmode/mediawiki-el#31]
The latest version of `mediawiki.el` available at https://stable.melpa.org/#/mediawiki is 2.2.5, because no versions since then have been tagged here on GitHub.  Could you add the missing tags, please?

**Comment by hexmode** [comment]
Tagged 2.2.9.

I'm not familiar with how stable melpa works or if I need to do anything else.  Let me know if melpa doesn't update.

**Comment by mavit** [comment]
That’s all you need to do, thanks.  [MELPA](https://melpa.org/#/mediawiki) watches your Git repository and automatically builds a package from every commit, whereas [MELPA Stable](https://stable.melpa.org/#/mediawiki) builds packages only for commits tagged with something that looks like a version number.
