### ISSUE TITLE
Cannot save pages on MW 1.32

### ISSUE THREAD

**Issue by ecraven** [hexmode/mediawiki-el#32]
It seems that `intoken` on `query` is not implemented any longer, you'd need to use the `token` endpoint. Opening any page in a 1.32 mediawiki says I cannot edit it (even if my user definitely can).

**Comment by biffhero** [comment]
I am having this problem as well.  Here is the output from when I set mediawiki-debug to t.

HTTP/1.1 200 OK
Date: Mon, 11 Feb 2019 02:31:22 GMT
Server: Apache/2.4.38 (Debian)
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Content-Disposition: inline; filename=api-result.xml
Cache-Control: private, must-revalidate, max-age=0
Content-Length: 376
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api batchcomplete=""><warnings><main xml:space="preserve">Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.</main><info xml:space="preserve">The parameter &quot;intoken&quot; has been deprecated.</info></warnings></api>

**Comment by hexmode** [comment]
I'm able to save on current emacs.

**Comment by hexmode** [comment]
(I should add: after changes made this past weekend.)
