### ISSUE TITLE
Errors while saving should be shown to the user (e.g. "Need an edit token", "Action 'edit' is not allowed for the current user")

### ISSUE THREAD

**Issue by DrChr** [hexmode/mediawiki-el#4]
Hi,
I'm trying to get mediawiki-el working in Emacs with my company's internal wiki. I've been able to open/edit/save a page using the mediawiki mode at e.g. the site wikemacs.org. However, when I try it on our company wiki, saving a modified wiki page fails with the following failure message (as seen from buffer _messages_)

```
  mediawiki-save-page: Need an edit token!
```

Notes:
- The company wiki connects through an HTTPS-address. 
- After entering my password I am able to open a wiki page from Emacs and see the source of the wiki page. 
- The error occurs when I try to use e.g. 'C-x C-s', i.e. 'M-x mediawiki-save'
- Unsure if it matters, but the wiki server doesn't have a proper certificate, so TLS connection tries a few different approaches before it works. See _messages_ below.
- We have set the following to configuration variables to true:
  - $wgEnableAPI
  - $wgEnableWriteAPI

Any help is appreciated, and please let me know if I should be using a different forum.
/Christian

Further down is an excerpt from the buffer _messages_ when doing 'M-x mediawiki-site'. I've replaced the real URL with 'xxx.yyy.com' and e.g. the URL for the main wiki page is as follows:

```
    https://xxx.yyy.com/wiki/index.php?title=Main_Page
```

Here is the excerpt from _messages_:

```
Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
Opening TLS connection to `xxx.yyy.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 xxx.yyy.com'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 xxx.yyy.com --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect xxx.yyy.com:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `xxx.yyy.com'...done
```

**Comment by hexmode** [comment]
Could you turn on debugging and then send me the contents of any buffers
produced, eliding private information, of course.

See M-x customize-variable RET mediawiki-debug RET

**Comment by DrChr** [comment]
Hi Mark,
Thanks for responding. I gave it a try from home, a different an Ubuntu
laptop. I installed mediawiki.el but didn't get it to work at all, not sure
what's going on here. The error message is different compare to before, and
I'm not even able to access wikemacs.org.  So I'll try again from the first
machine on Monday.

Best regards,
Christian

PS.
For completeness, this is what I get



On 9 January 2016 at 18:35, Mark A. Hershberger <notifications@github.com>
wrote:

>
> Could you turn on debugging and then send me the contents of any buffers
> produced, eliding private information, of course.
>
> See M-x customize-variable RET mediawiki-debug RET
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexmode/mediawiki-el/issues/4#issuecomment-170263648>.
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by DrChr** [comment]
Oops, hit 'send' to early. Here's the rest - first the response get when
trying to access wikemacs.org from Ubuntu and I can't load the wiki source:

Posting to: http://wikemacs.org/wiki/api.php
Contacting host: wikemacs.org:80
Examine the ' *http wikemacs.org:80*-598319' buffer called from
'url-http-response-post-process:3'.
mediawiki-api-call: There was an error parsing the result of the API call


Note: I was expecting something to be found in a buffer called '*http
wikemacs....*, but I don't see that buffer?
I

Below is also the response I get when trying to access my work site:

Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
Examine the ' *http xxx.yyy.com:443*-200992' buffer called from
'url-http-response-post-process:3'.
Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
Examine the ' *http xxx.yyy.com:443*-45445' buffer called from
'url-http-response-post-process:3'.
Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
Examine the ' *http xxx.yyy.com:443*-865948' buffer called from
'url-http-response-post-process:3'.
mediawiki-api-call: The server encountered an error: (readapidenied) You
need read permission to use this module



Best regards,
Christian


On 10 January 2016 at 01:52, Christian Ridderström <
christian.ridderstrom@gmail.com> wrote:

> Hi Mark,
> Thanks for responding. I gave it a try from home, a different an Ubuntu
> laptop. I installed mediawiki.el but didn't get it to work at all, not sure
> what's going on here. The error message is different compare to before, and
> I'm not even able to access wikemacs.org.  So I'll try again from the
> first machine on Monday.
>
> Best regards,
> Christian
>
> PS.
> For completeness, this is what I get
>
>
>
> On 9 January 2016 at 18:35, Mark A. Hershberger <notifications@github.com>
> wrote:
>
>>
>> Could you turn on debugging and then send me the contents of any buffers
>> produced, eliding private information, of course.
>>
>> See M-x customize-variable RET mediawiki-debug RET
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hexmode/mediawiki-el/issues/4#issuecomment-170263648>
>> .
>>
>
>
>
> --
> Christian Ridderström,     +46-70 687 39 44
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by hexmode** [comment]
DrChr writes:

> Posting to: http://wikemacs.org/wiki/api.php

The url needs to be set to "http://wikemacs.org/" not
"http://wikemacs.org/wiki/".

To fix this issue, I need to set up a sniffer that will see if you
pointed it to the wiki instead of the API and find the <link> element with
EditURI and use that.

You can see this if you view-source on the page.  There will be:

    <link rel="EditURI" type="application/rsd+xml" href="http://wikemacs.org/api.php?action=rsd" />

mediawiki.el and WikEmacs still don't work completely, though, because
of the captcha.

> Note: I was expecting something to be found in a buffer called '*http
> wikemacs....*, but I don't see that buffer?

The buffer is hidden because it starts with a space.  See
http://www.emacswiki.org/emacs/InvisibleBuffers

**Comment by DrChr** [comment]
On 10 January 2016 at 13:34, Mark A. Hershberger <notifications@github.com>
wrote:

>
> DrChr writes:
>
> > Posting to: http://wikemacs.org/wiki/api.php
>
> The url needs to be set to "http://wikemacs.org/" not
> "http://wikemacs.org/wiki/".
>

Ok, I understand.Btw, the wiki page: http://wikemacs.org/wiki/Mediawiki.el
uses an incorrect(?) URL in the example for wikemacs, it says "
http://wikemacs.org/w/".  Can I change this to "http://wikemacs.org/"?

With the correct URL I can now open, edit and save e.g.
http://wikemacs.org/wiki/WikEmacs:Scratch_Buffer


> To fix this issue, I need to set up a sniffer that will see if you
> pointed it to the wiki instead of the API and find the <link> element with
> EditURI and use that.
>
> You can see this if you view-source on the page. There will be:
>
> <link rel="EditURI" type="application/rsd+xml" href="
> http://wikemacs.org/api.php?action=rsd" />
>

Yes, you're correct. It is indeed tricky when links are being redirected.

Would it make sense to add some kind of troubleshooting tip to e.g.
http://wikemacs.org/wiki/Mediawiki.el regarding how to check if you've
correctly specified the URI of the site?



> mediawiki.el and WikEmacs still don't work completely, though, because
> of the captcha.
>

If so, how come I was able to edit the scratch page - no authentification
needed for the scratch page?


> > Note: I was expecting something to be found in a buffer called '*http
> > wikemacs....*, but I don't see that buffer?
>
> The buffer is hidden because it starts with a space. See
> http://www.emacswiki.org/emacs/InvisibleBuffers


Thanks, very neat.


Going back towards my original topic and the wiki at my work, I looked at
the ' *http'-buffers, appended at the end in case you're interested. One of
them said
    login result="NotExists"
so I double checked my credentials. I'd spelled my username in all caps
(bad habit from aerospace docs). Turns out the username is (partially) case
sensitive.
So thanks for making me look at the debug windows, the original message
isn't so easy:
  let*: The server encountered an error: (readapidenied) You need read
permission to use this module

I'm still not able to save a page to my work wiki, but I'll reply
separately on that topic, now that I'll look at the debug buffers.

Best regards,
Christian

---------- Excerpt from: *Messages* ----------
Posting to: https://yyy.xxx.com/wiki/api.php
Contacting host: yyy.xxx.com:443
Examine the ' *http yyy.xxx.com:443*' buffer called from
'url-http-response-post-process:3'.
Posting to: https://yyy.xxx.com/wiki/api.php
Contacting host: yyy.xxx.com:443
Examine the ' *http yyy.xxx.com:443*-219914' buffer called from
'url-http-response-post-process:3'.
Posting to: https://yyy.xxx.com/wiki/api.php
Contacting host: yyy.xxx.com:443
Examine the ' *http yyy.xxx.com:443*-776559' buffer called from
'url-http-response-post-process:3'.
let*: The server encountered an error: (readapidenied) You need read
permission to use this module


---------- Excerpt from: ' *http yyy.xxx.com:443*' ----------
HTTP/1.1 200 OK
Date: Sun, 10 Jan 2016 21:51:16 GMT
Server: Apache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Cache-Control: private
Vary: Accept-Encoding
X-Powered-By: PleskLin
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api><login result="NeedToken"
token="074459ce7717ca27e14f0b0f4886445a" cookieprefix="mediawiki_9_wiki_"
sessionid="e7e6231le3149liglnibg88nk6" /></api>

---------- Excerpt from: ' *http yyy.xxx.com:443*-219914' ----------
HTTP/1.1 200 OK
Date: Sun, 10 Jan 2016 21:51:17 GMT
Server: Apache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Cache-Control: private
Vary: Accept-Encoding
X-Powered-By: PleskLin
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api><login result="NotExists" /></api>

---------- Excerpt from: ' *http yyy.xxx.com:443*-776559' ----------
HTTP/1.1 200 OK
Date: Sun, 10 Jan 2016 21:51:17 GMT
Server: Apache
X-Content-Type-Options: nosniff
MediaWiki-API-Error: readapidenied
X-Frame-Options: DENY
Cache-Control: private
Vary: Accept-Encoding
X-Powered-By: PleskLin
Connection: close
Transfer-Encoding: chunked
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api><error code="readapidenied" info="You need read
permission to use this module" /></api>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by DrChr** [comment]
Ok, now I can open a page from the work wiki, but still not save. So I've
continued to troubleshoot - but with debug on:
-------------
<?xml version="1.0"?><api><warnings><info xml:space="preserve">Action
'edit' is not allowed for the current
user</info></warnings><query><pages><page pageid="153" ns="0" title="Main
Page" contentmodel="wikitext" pagelanguage="en"
touched="2015-12-09T09:20:32Z" lastrevid="4526" counter="3944"
length="2350" starttimestamp="2016-01-10T22:28:29Z"><revisions><rev
revid="4526" parentid="4524" user="Alex" timestamp="2015-12-09T09:20:32Z"
comment="/* Övrigt/Dokumentation */" contentformat="text/x-wiki"
contentmodel="wikitext" xml:space="preserve">&lt;br&gt;&lt;br&gt;
-------------

Turns out my account isn't allowed to edit the work wiki *sigh*.

I was previously using another account, and when my colleague recently
created a new one for me (name needed changing), he forgot to enable
editing.  However, using the browsers I was still able to edit the wiki, as
the browser remembered the old account's credentials, and that account was
allowed to edit wiki pages.

So when logging in with my old account credentials, I was able to open a
wiki page in Emacs, modify it and save it back to the wiki. This topic can
be closed now :-)

Many thanks for the help Mark!
/Christian

PS.
It probably would be possible to make the mode recognize the API warning
about edit not being allowed, and e.g. flag this through making the Emacs
buffer read only (with a message).







On 10 January 2016 at 23:26, Christian Ridderström <
christian.ridderstrom@gmail.com> wrote:

>
> On 10 January 2016 at 13:34, Mark A. Hershberger <notifications@github.com
> > wrote:
>
>>
>> DrChr writes:
>>
>> > Posting to: http://wikemacs.org/wiki/api.php
>>
>> The url needs to be set to "http://wikemacs.org/" not
>> "http://wikemacs.org/wiki/".
>>
>
> Ok, I understand.Btw, the wiki page: http://wikemacs.org/wiki/Mediawiki.el
> uses an incorrect(?) URL in the example for wikemacs, it says "
> http://wikemacs.org/w/".  Can I change this to "http://wikemacs.org/"?
>
> With the correct URL I can now open, edit and save e.g.
> http://wikemacs.org/wiki/WikEmacs:Scratch_Buffer
>
>
>> To fix this issue, I need to set up a sniffer that will see if you
>> pointed it to the wiki instead of the API and find the <link> element with
>> EditURI and use that.
>>
>> You can see this if you view-source on the page. There will be:
>>
>> <link rel="EditURI" type="application/rsd+xml" href="
>> http://wikemacs.org/api.php?action=rsd" />
>>
>
> Yes, you're correct. It is indeed tricky when links are being redirected.
>
> Would it make sense to add some kind of troubleshooting tip to e.g.
> http://wikemacs.org/wiki/Mediawiki.el regarding how to check if you've
> correctly specified the URI of the site?
>
>
>
>> mediawiki.el and WikEmacs still don't work completely, though, because
>> of the captcha.
>>
>
> If so, how come I was able to edit the scratch page - no authentification
> needed for the scratch page?
>
>
>> > Note: I was expecting something to be found in a buffer called '*http
>> > wikemacs....*, but I don't see that buffer?
>>
>> The buffer is hidden because it starts with a space. See
>> http://www.emacswiki.org/emacs/InvisibleBuffers
>
>
> Thanks, very neat.
>
>
> Going back towards my original topic and the wiki at my work, I looked at
> the ' *http'-buffers, appended at the end in case you're interested. One of
> them said
>     login result="NotExists"
> so I double checked my credentials. I'd spelled my username in all caps
> (bad habit from aerospace docs). Turns out the username is (partially) case
> sensitive.
> So thanks for making me look at the debug windows, the original message
> isn't so easy:
>   let*: The server encountered an error: (readapidenied) You need read
> permission to use this module
>
> I'm still not able to save a page to my work wiki, but I'll reply
> separately on that topic, now that I'll look at the debug buffers.
>
> Best regards,
> Christian
>
> ---------- Excerpt from: *Messages* ----------
> Posting to: https://yyy.xxx.com/wiki/api.php
> Contacting host: yyy.xxx.com:443
> Examine the ' *http yyy.xxx.com:443*' buffer called from
> 'url-http-response-post-process:3'.
> Posting to: https://yyy.xxx.com/wiki/api.php
> Contacting host: yyy.xxx.com:443
> Examine the ' *http yyy.xxx.com:443*-219914' buffer called from
> 'url-http-response-post-process:3'.
> Posting to: https://yyy.xxx.com/wiki/api.php
> Contacting host: yyy.xxx.com:443
> Examine the ' *http yyy.xxx.com:443*-776559' buffer called from
> 'url-http-response-post-process:3'.
> let*: The server encountered an error: (readapidenied) You need read
> permission to use this module
>
>
> ---------- Excerpt from: ' *http yyy.xxx.com:443*' ----------
> HTTP/1.1 200 OK
> Date: Sun, 10 Jan 2016 21:51:16 GMT
> Server: Apache
> X-Content-Type-Options: nosniff
> X-Frame-Options: DENY
> Cache-Control: private
> Vary: Accept-Encoding
> X-Powered-By: PleskLin
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: text/xml; charset=utf-8
>
> <?xml version="1.0"?><api><login result="NeedToken"
> token="074459ce7717ca27e14f0b0f4886445a" cookieprefix="mediawiki_9_wiki_"
> sessionid="e7e6231le3149liglnibg88nk6" /></api>
>
> ---------- Excerpt from: ' *http yyy.xxx.com:443*-219914' ----------
> HTTP/1.1 200 OK
> Date: Sun, 10 Jan 2016 21:51:17 GMT
> Server: Apache
> X-Content-Type-Options: nosniff
> X-Frame-Options: DENY
> Cache-Control: private
> Vary: Accept-Encoding
> X-Powered-By: PleskLin
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: text/xml; charset=utf-8
>
> <?xml version="1.0"?><api><login result="NotExists" /></api>
>
> ---------- Excerpt from: ' *http yyy.xxx.com:443*-776559' ----------
> HTTP/1.1 200 OK
> Date: Sun, 10 Jan 2016 21:51:17 GMT
> Server: Apache
> X-Content-Type-Options: nosniff
> MediaWiki-API-Error: readapidenied
> X-Frame-Options: DENY
> Cache-Control: private
> Vary: Accept-Encoding
> X-Powered-By: PleskLin
> Connection: close
> Transfer-Encoding: chunked
> Content-Type: text/xml; charset=utf-8
>
> <?xml version="1.0"?><api><error code="readapidenied" info="You need read
> permission to use this module" /></api>
>
>
>
> --
> Christian Ridderström,     +46-70 687 39 44
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by hexmode** [comment]
(Tried editing your email, but evidently markdown isn't supported :( )

I'm re-purposing the bug for your P.S.

**Comment by hexmode** [comment]
should be fixed in recent code.
