### ISSUE TITLE
url-http: Could not create connection to labs.profoto.com:443

### ISSUE THREAD

**Issue by DrChr** [hexmode/mediawiki-el#5]
Hi Mark,

I am able to access the internal wiki of my office from my Mac as well as from Ubuntu. 
From Windows 7 I am only able to open and edit e.g. the page 'Scratch Buffer' on http://wikemacs.org, so 'mediawiki' is at least basically installed.  However, when I try to open a page from my work wiki, whose URL I'll denote:  `https://xxx.yyy.com/wiki/`, emacs/mediawiki fails to create a connection.

Specifically, when doing 'M-x mediawiki-site xxx', I get the following from the buffer _Messages_:

```
Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
gnutls.c: [1] (Emacs) GnuTLS library not found
Opening TLS connection to `xxx.yyy.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 xxx.yyy.com'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 xxx.yyy.com --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect xxx.yyy.com:443 -no_ssl2 -ign_eof'...failed
Opening TLS connection to `xxx.yyy.com'...failed
url-http: Could not create connection to xxx.yyy.com:443
```

I then tried the same after enabling debug messages, i.e. doing `M-x customize-variable mediawiki-debug` and setting the variable to non-nil. Then I re-ran 'M-x mediawiki ...' and expected to get some buffers called e.g. ' *htttp ....', but they're not created. I assume it's because the HTTPS connection isn't working properly.

Perhaps I don't easily have SSL support when on Windows 7?    (I do have PuTTy and Git bash installed, maybe I can make Emacs use their libs somehow).

Best regards,
Christian

PS. It's not necessary for me to get 'mediawiki' working from Windows, but I thought why not see if I can get it working from all three platforms.

**Comment by hexmode** [comment]
It looks like you are missing the gnutls-cli binary, but see http://חנוך.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html 
and see if it it helps you with this. 

----- Original Message -----

> Hi Mark,

> I am able to access the internal wiki of my office from my Mac as well as
> from Ubuntu
> From Windows 7 I am only able to open and edit eg the page 'Scratch Buffer'
> on http://wikemacsorg, so 'mediawiki' is at least basically installed
> However, when I try to open a page from my work wiki, whose URL I'll denote:
> https://xxxyyycom/wiki/ , emacs/mediawiki fails to create a connection

> Specifically, when doing 'M-x mediawiki-site xxx', I get the following from
> the buffer Messages :
> Posting to: https://xxxyyycom/wiki/apiphp
> Contacting host: xxxyyycom:443
> gnutlsc: [1] (Emacs) GnuTLS library not found
> Opening TLS connection to `xxxyyycom'
> Opening TLS connection with `gnutls-cli --insecure -p 443 xxxyyycom'failed
> Opening TLS connection with `gnutls-cli --insecure -p 443 xxxyyycom
> --protocols ssl3'failed
> Opening TLS connection with `openssl s_client -connect xxxyyycom:443 -no_ssl2
> -ign_eof'failed
> Opening TLS connection to `xxxyyycom'failed
> url-http: Could not create connection to xxxyyycom:443

> I then tried the same after enabling debug messages, ie doing M-x
> customize-variable mediawiki-debug and setting the variable to non-nil Then
> I re-ran 'M-x mediawiki ' and expected to get some buffers called eg '
> *htttp ', but they're not created I assume it's because the HTTPS connection
> isn't working properly

> Perhaps I don't easily have SSL support when on Windows 7? (I do have PuTTy
> and Git bash installed, maybe I can make Emacs use their libs somehow)

> Best regards,
> Christian

> PS It's not necessary for me to get 'mediawiki' working from Windows, but I
> thought why not see if I can get it working from all three platforms

> —
> Reply to this email directly or view it on GitHub .

-- 
Mark A. Hershberger 
NicheWork LLC 
717-271-1084
