### ISSUE TITLE
Error message "Bad token" received when trying to save a little while later

### ISSUE THREAD

**Issue by DrChr** [hexmode/mediawiki-el#7]
I'm using 'mediawiki' in Emacs to edit a wiki page on an internal wiki at work. 
I am able to open the wiki page in Emacs, edit it, save it. Then I can continue to work on the page, saving it now and then. After a while, I am no longer able to save the page and instead get the following error message (from buffer _Messages_ with debug on):

```
Posting to: https://xxx.yyy.com/wiki/api.php
Contacting host: xxx.yyy.com:443
Examine the ' *http xxx.yyy.com:443*-954102' buffer called from 'url-http-response-post-process:3'.
mediawiki-api-call: The server encountered an error: (badtoken) Invalid token
```

And below is the text from a buffer like `* http xxx.yyy.com:443`.

```
HTTP/1.1 200 OK
Date: Mon, 11 Jan 2016 17:09:35 GMT
Server: Apache
X-Content-Type-Options: nosniff
MediaWiki-API-Error: badtoken
X-Frame-Options: DENY
Cache-Control: private
Vary: Accept-Encoding
Content-Encoding: gzip
X-Powered-By: PleskLin
Content-Length: 91
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api><error code="badtoken" info="Invalid token" /></api>
```

Not sure what's going on, but perhaps there's a time limit on the token that allows Emacs to upload changes to a wiki page?   Is there a way I can trigger 'mediawiki.el' to obtain a fresh token?

Regards,
Christian

**Comment by hexmode** [comment]
You can save your work (copy the entire buffer somewhere or just yank it all) and then hit M-g to refresh the buffer. The old content should be restored. Move point to the beginning of the buffer, clear the buffer, and then insert your new content and save. 

Yes, I've done this a few times and there really should be a better way.

**Comment by DrChr** [comment]
For me it doesn't work with 'M-g', I get an error message (can't see it
right now, but will post it in a separate mail the next time I see it).

I have however noticed that I can do this sequence to "recover":
* Yank the entire buffer (or copy it somewhere temporarily)
* 'M-x mediawiki-site Wikipedia'
* 'M-x mediawiki-site myJobSite'
* 'C-c C-o Page name'  to open the page again
* Remove existing text and paste in the previous version
* 'C-x C-s'  to save it to the wiki

The problem just happened again, and it had only been 5-10 minutes since I
opened the page initially. So it's quite annoying.

/Christian


On 11 January 2016 at 18:32, Mark A. Hershberger <notifications@github.com>
wrote:

> You can save your work (copy the entire buffer somewhere or just yank it
> all) and then hit M-g to refresh the buffer. The old content should be
> restored. Move point to the beginning of the buffer, clear the buffer, and
> then insert your new content and save.
>
> Yes, I've done this a few times and there really should be a better way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexmode/mediawiki-el/issues/7#issuecomment-170627101>.
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by DrChr** [comment]
It took longer this time, but now I got the error again.
So I tried the 'M-g', and got an error message. I've pasted in the
corresponding debug buffer below.

Regards,
Christian
```
HTTP/1.1 200 OK
Date: Tue, 12 Jan 2016 16:57:36 GMT
Server: Apache
X-Content-Type-Options: nosniff
MediaWiki-API-Error: readapidenied
X-Frame-Options: DENY
Cache-Control: private
Vary: Accept-Encoding
Content-Encoding: gzip
X-Powered-By: PleskLin
Content-Length: 114
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version="1.0"?><api><error code="readapidenied" info="You need read
permission to use this module" /></api>
```

On 12 January 2016 at 17:06, Christian Ridderström <
christian.ridderstrom@gmail.com> wrote:

> For me it doesn't work with 'M-g', I get an error message (can't see it
> right now, but will post it in a separate mail the next time I see it).
>
> I have however noticed that I can do this sequence to "recover":
> * Yank the entire buffer (or copy it somewhere temporarily)
> * 'M-x mediawiki-site Wikipedia'
> * 'M-x mediawiki-site myJobSite'
> * 'C-c C-o Page name'  to open the page again
> * Remove existing text and paste in the previous version
> * 'C-x C-s'  to save it to the wiki
>
> The problem just happened again, and it had only been 5-10 minutes since I
> opened the page initially. So it's quite annoying.
>
> /Christian
>
>
> On 11 January 2016 at 18:32, Mark A. Hershberger <notifications@github.com
> > wrote:
>
>> You can save your work (copy the entire buffer somewhere or just yank it
>> all) and then hit M-g to refresh the buffer. The old content should be
>> restored. Move point to the beginning of the buffer, clear the buffer, and
>> then insert your new content and save.
>>
>> Yes, I've done this a few times and there really should be a better way.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hexmode/mediawiki-el/issues/7#issuecomment-170627101>
>> .
>>
>
>
>
> --
> Christian Ridderström,     +46-70 687 39 44
>



-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by DrChr** [comment]
Hi Mark

This error is rather annoying. I think I'd like to troubleshoot it a bit,
to see if I can find a better workaround at least. Any suggestions on how I
should start?

Is there for instance some way to trigger obtaining a new token? Or is
there a token for each buffer (instrad of one per site)?

Regards
Christian

On Tuesday, 12 January 2016, Christian Ridderström <
christian.ridderstrom@gmail.com> wrote:

> It took longer this time, but now I got the error again.
> So I tried the 'M-g', and got an error message. I've pasted in the
> corresponding debug buffer below.
>
> Regards,
> Christian
> ```
> HTTP/1.1 200 OK
> Date: Tue, 12 Jan 2016 16:57:36 GMT
> Server: Apache
> X-Content-Type-Options: nosniff
> MediaWiki-API-Error: readapidenied
> X-Frame-Options: DENY
> Cache-Control: private
> Vary: Accept-Encoding
> Content-Encoding: gzip
> X-Powered-By: PleskLin
> Content-Length: 114
> Connection: close
> Content-Type: text/xml; charset=utf-8
>
> <?xml version="1.0"?><api><error code="readapidenied" info="You need read
> permission to use this module" /></api>
> ```
>
> On 12 January 2016 at 17:06, Christian Ridderström <
> christian.ridderstrom@gmail.com
> <javascript:_e(%7B%7D,'cvml','christian.ridderstrom@gmail.com');>> wrote:
>
>> For me it doesn't work with 'M-g', I get an error message (can't see it
>> right now, but will post it in a separate mail the next time I see it).
>>
>> I have however noticed that I can do this sequence to "recover":
>> * Yank the entire buffer (or copy it somewhere temporarily)
>> * 'M-x mediawiki-site Wikipedia'
>> * 'M-x mediawiki-site myJobSite'
>> * 'C-c C-o Page name'  to open the page again
>> * Remove existing text and paste in the previous version
>> * 'C-x C-s'  to save it to the wiki
>>
>> The problem just happened again, and it had only been 5-10 minutes since
>> I opened the page initially. So it's quite annoying.
>>
>> /Christian
>>
>>
>> On 11 January 2016 at 18:32, Mark A. Hershberger <
>> notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> You can save your work (copy the entire buffer somewhere or just yank it
>>> all) and then hit M-g to refresh the buffer. The old content should be
>>> restored. Move point to the beginning of the buffer, clear the buffer, and
>>> then insert your new content and save.
>>>
>>> Yes, I've done this a few times and there really should be a better way.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/hexmode/mediawiki-el/issues/7#issuecomment-170627101>
>>> .
>>>
>>
>>
>>
>> --
>> Christian Ridderström,     +46-70 687 39 44
>>
>
>
>
> --
> Christian Ridderström,     +46-70 687 39 44
>


-- 
Christian Ridderström,     +46-70 687 39 44

**Comment by hexmode** [comment]
I'm confused. The title of this bug talks about a token, but the error
says "readapidenied" which is different.

Is emacs telling you that you have a bad token when the actual message
is you don't have permission?

>> <?xml version="1.0"?><api><error code="readapidenied" info="You need read
>> permission to use this module" /></api>

**Comment by DrChr** [comment]
Apologies for the confusion. The first error is indicated by invalid token.
IIRC there was nothing more in the debug buffers in this case (no buffers
created).

The error readapidenied is from when I try M-g as a way to work around
/ mitigate the effect of no longer having a token.

I should've created a separate (but related) issue for readapidenied. I'll
do so this weekend.
Cheers
Christian

On Friday, 15 January 2016, Mark A. Hershberger <notifications@github.com>
wrote:

>
> I'm confused. The title of this bug talks about a token, but the error
> says "readapidenied" which is different.
>
> Is emacs telling you that you have a bad token when the actual message
> is you don't have permission?
>
> >> <?xml version="1.0"?><api><error code="readapidenied" info="You need
> read
> >> permission to use this module" /></api>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexmode/mediawiki-el/issues/7#issuecomment-172008622>.
>


-- 
Christian Ridderström,     +46-70 687 39 44
